import React, { useState, useMemo } from "react";
import { ArrowLeft, CreditCard, ShoppingBag, ShieldCheck, Lock, CheckCircle2, AlertTriangle } from "lucide-react";
import { Product, CartItem, ProductVariant } from "../types";
import { useCartStore } from "../useCartStore";
import { createCheckoutSession } from "../createCheckoutSession";

interface CheckoutPageProps {
  products: Product[];
  onBack: () => void;
  onOrderPlaced: (orderId: string) => void;
}

export default function CheckoutPage({ products, onBack, onOrderPlaced }: CheckoutPageProps) {
  const { cartItems, clearCart } = useCartStore();

  // Address State
  const [fullName, setFullName] = useState("Quenton Simiyu");
  const [email, setEmail] = useState("quentonsimiyu254@gmail.com");
  const [phone, setPhone] = useState("+254 712 345 678");
  const [street, setStreet] = useState("1024 Kimathi Street");
  const [city, setCity] = useState("Nairobi");
  const [state, setState] = useState("Nairobi County");
  const [postalCode, setPostalCode] = useState("00100");
  const [country, setCountry] = useState("Kenya");
  
  // Payment Gateway
  const [gateway, setGateway] = useState<"stripe" | "paystack" | "mpesa">("mpesa");
  
  // Loading & Session Url states
  const [isGenerating, setIsGenerating] = useState(false);
  const [errorMsg, setErrorMsg] = useState("");

  // Resolve items in the cart
  const resolvedItems = useMemo(() => {
    return cartItems.map((item) => {
      const product = products.find((p) => p.id === item.productId);
      const variant = product?.variants.find((v) => v.id === item.variantId);
      return {
        item,
        product,
        variant,
      };
    }).filter(data => data.product && data.variant);
  }, [cartItems, products]);

  // Totals calculations
  const subtotal = useMemo(() => {
    return resolvedItems.reduce((acc, current) => {
      const price = current.variant?.priceOverride ? Number(current.variant.priceOverride) : current.product!.basePrice;
      return acc + price * current.item.quantity;
    }, 0);
  }, [resolvedItems]);

  const shippingThreshold = 150;
  const isShippingFree = subtotal >= shippingThreshold;
  const shippingCost = subtotal > 0 ? (isShippingFree ? 0.00 : 15.00) : 0.00;
  const taxCost = subtotal * 0.08; // 8% FLAT V.A.T
  const grandTotal = subtotal + shippingCost + taxCost;

  const handleCheckoutSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (resolvedItems.length === 0) {
      setErrorMsg("Your cart is empty. Curate styling before processing payment.");
      return;
    }

    setIsGenerating(true);
    setErrorMsg("");

    try {
      // Initiate secure payment and database order tracking via Server Action
      const data = await createCheckoutSession({
        fullName,
        email,
        phone,
        shippingAddress: `${street}, ${city}, ${state}, ${postalCode}, ${country}`,
        gateway,
        cartItems: cartItems,
      });
      
      if (data.checkoutUrl) {
        // Redirect client to secure stripe/paystack checkout simulation page
        window.location.href = data.checkoutUrl;
      } else {
        throw new Error("Invalid payload generated by authorization servers.");
      }
    } catch (err: any) {
      console.error("Secure payment routing issue:", err);
      setErrorMsg(err.message || "Stripe gateway handshake failed. Verify networking or try again.");
      setIsGenerating(false);
    }
  };

  return (
    <div id="checkout-view-container" className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 py-10 animate-fade-in select-none">
      
      {/* Back tracking Header */}
      <div className="flex items-center justify-between mb-8 pb-4 border-b border-neutral-100">
        <button
          id="checkout-back-link"
          onClick={onBack}
          className="inline-flex items-center gap-2 text-xs font-mono uppercase tracking-widest text-neutral-500 hover:text-neutral-900 transition-colors py-1 focus:outline-hidden"
        >
          <ArrowLeft className="h-4 w-4" />
          Review Curated Bag
        </button>
        <span className="text-[11px] font-mono uppercase tracking-widest text-neutral-400">
          SECURE ENCRYPTED CHECKOUT (SSL)
        </span>
      </div>

      {resolvedItems.length === 0 ? (
        <div className="text-center py-24 bg-neutral-50 rounded-lg border border-dashed border-neutral-200">
          <ShoppingBag className="h-8 w-8 text-neutral-300 mx-auto mb-3" />
          <h3 className="font-sans font-bold text-sm text-neutral-800 uppercase tracking-wider">Checkout Cart Empty</h3>
          <p className="text-xs text-neutral-400 mt-1 max-w-xs mx-auto">
            You do not have any items marked for booking. Select a curated item to begin.
          </p>
          <button
            onClick={onBack}
            className="mt-4 rounded bg-dark py-2.5 px-6 text-xs font-bold uppercase tracking-wider text-white"
          >
            Go back
          </button>
        </div>
      ) : (
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
          
          {/* Left Column: Delivery Form Coordinates (Col Span 7) */}
          <form onSubmit={handleCheckoutSubmit} className="lg:col-span-7 space-y-6">
            <div className="bg-white rounded-lg border border-neutral-150 p-6 space-y-5">
              <div className="border-b border-neutral-100 pb-3 flex items-center gap-2">
                <CheckCircle2 className="h-4 w-4 text-kiwi shrink-0" />
                <h3 className="text-sm font-bold uppercase tracking-wider text-neutral-900 font-sans">
                  Shipping Coordinates
                </h3>
              </div>

              {errorMsg && (
                <div className="p-3 bg-red-50 text-red-600 rounded text-xs border border-red-200 flex items-center gap-2">
                  <AlertTriangle className="h-4 w-4 shrink-0" />
                  <span>{errorMsg}</span>
                </div>
              )}

              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 text-xs font-sans">
                <div className="sm:col-span-2">
                  <label className="block font-semibold text-neutral-700 mb-1">Full Delivery Name</label>
                  <input
                    type="text"
                    required
                    value={fullName}
                    onChange={(e) => setFullName(e.target.value)}
                    className="w-full text-xs p-2.5 rounded border border-neutral-350 bg-white focus:ring-1 focus:ring-dark focus:outline-hidden"
                  />
                </div>

                <div>
                  <label className="block font-semibold text-neutral-700 mb-1">Email (Secure receipt distribution)</label>
                  <input
                    type="email"
                    required
                    value={email}
                    onChange={(e) => setEmail(e.target.value)}
                    className="w-full text-xs p-2.5 rounded border border-neutral-350 bg-white focus:ring-1 focus:ring-dark focus:outline-hidden"
                  />
                </div>

                <div>
                  <label className="block font-semibold text-neutral-700 mb-1">Contact Phone</label>
                  <input
                    type="text"
                    required
                    value={phone}
                    onChange={(e) => setPhone(e.target.value)}
                    className="w-full text-xs p-2.5 rounded border border-neutral-350 bg-white focus:ring-1 focus:ring-dark focus:outline-hidden"
                  />
                </div>

                <div className="sm:col-span-2">
                  <label className="block font-semibold text-neutral-700 mb-1">Street Address</label>
                  <input
                    type="text"
                    required
                    placeholder="Apartment, suite, block unit or street name"
                    value={street}
                    onChange={(e) => setStreet(e.target.value)}
                    className="w-full text-xs p-2.5 rounded border border-neutral-350 bg-white focus:ring-1 focus:ring-dark focus:outline-hidden"
                  />
                </div>

                <div>
                  <label className="block font-semibold text-neutral-700 mb-1">City</label>
                  <input
                    type="text"
                    required
                    value={city}
                    onChange={(e) => setCity(e.target.value)}
                    className="w-full text-xs p-2.5 rounded border border-neutral-350 bg-white focus:ring-1 focus:ring-dark focus:outline-hidden"
                  />
                </div>

                <div>
                  <label className="block font-semibold text-neutral-700 mb-1">State / Province</label>
                  <input
                    type="text"
                    required
                    value={state}
                    onChange={(e) => setState(e.target.value)}
                    className="w-full text-xs p-2.5 rounded border border-neutral-350 bg-white focus:ring-1 focus:ring-dark focus:outline-hidden"
                  />
                </div>

                <div>
                  <label className="block font-semibold text-neutral-700 mb-1">Postcode / ZIP</label>
                  <input
                    type="text"
                    required
                    value={postalCode}
                    onChange={(e) => setPostalCode(e.target.value)}
                    className="w-full text-xs p-2.5 rounded border border-neutral-350 bg-white focus:ring-1 focus:ring-dark focus:outline-hidden"
                  />
                </div>

                <div>
                  <label className="block font-semibold text-neutral-700 mb-1">Country</label>
                  <input
                    type="text"
                    required
                    value={country}
                    onChange={(e) => setCountry(e.target.value)}
                    className="w-full text-xs p-2.5 rounded border border-neutral-350 bg-white focus:ring-1 focus:ring-dark focus:outline-hidden"
                  />
                </div>
              </div>
            </div>

            {/* Gateway selectors */}
            <div className="bg-white rounded-lg border border-neutral-150 p-6 space-y-4">
              <div className="border-b border-neutral-100 pb-3 flex items-center gap-2">
                <Lock className="h-4 w-4 text-kiwi shrink-0" />
                <h3 className="text-sm font-bold uppercase tracking-wider text-neutral-900 font-sans">
                  Secure Billing Handlers
                </h3>
              </div>

              <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
                {/* M-Pesa Options */}
                <button
                  type="button"
                  id="checkout-gateway-mpesa"
                  onClick={() => setGateway("mpesa")}
                  className={`p-4 rounded-lg border text-left flex flex-col justify-between h-24 transition-all ${
                    gateway === "mpesa"
                      ? "border-neutral-900 bg-neutral-900 text-white ring-2 ring-kiwi"
                      : "border-neutral-200 hover:border-neutral-400 bg-white text-neutral-800"
                  }`}
                >
                  <div className="flex items-center gap-1.5 font-bold uppercase text-[10px] tracking-widest leading-none">
                    <span className="h-2 w-2 rounded-full bg-emerald-500"></span>
                    M-Pesa Direct
                  </div>
                  <span className="text-[10px] text-neutral-400 font-sans leading-snug">
                    Pay directly to M-Pesa phone: <strong>0745892776</strong>
                  </span>
                </button>

                {/* Stripe Options */}
                <button
                  type="button"
                  id="checkout-gateway-stripe"
                  onClick={() => setGateway("stripe")}
                  className={`p-4 rounded-lg border text-left flex flex-col justify-between h-24 transition-all ${
                    gateway === "stripe"
                      ? "border-neutral-900 bg-neutral-900 text-white ring-2 ring-kiwi"
                      : "border-neutral-200 hover:border-neutral-400 bg-white text-neutral-800"
                  }`}
                >
                  <div className="flex items-center gap-1.5 font-bold uppercase text-[10px] tracking-widest leading-none">
                    <span className="h-2 w-2 rounded-full bg-blue-500"></span>
                    Stripe Gateway
                  </div>
                  <span className="text-[10px] text-neutral-400 font-sans leading-snug">
                    Cards & Digital wallets (Visa, Mastercard, Apple Pay)
                  </span>
                </button>

                {/* Paystack Options */}
                <button
                  type="button"
                  id="checkout-gateway-paystack"
                  onClick={() => setGateway("paystack")}
                  className={`p-4 rounded-lg border text-left flex flex-col justify-between h-24 transition-all ${
                    gateway === "paystack"
                      ? "border-neutral-900 bg-neutral-900 text-white ring-2 ring-kiwi"
                      : "border-neutral-200 hover:border-neutral-400 bg-white text-neutral-800"
                  }`}
                >
                  <div className="flex items-center gap-1.5 font-bold uppercase text-[10px] tracking-widest leading-none">
                    <span className="h-2 w-2 rounded-full bg-teal-500"></span>
                    Paystack
                  </div>
                  <span className="text-[10px] text-neutral-400 font-sans leading-snug">
                    Regional processor integration (Cards, EFT transfers)
                  </span>
                </button>
              </div>
            </div>

            {/* Submit Action */}
            <button
              type="submit"
              disabled={isGenerating}
              className="w-full bg-neutral-950 text-white rounded-md h-12 flex items-center justify-center gap-2.5 hover:bg-neutral-850 active:scale-98 transition-all shadow-sm font-semibold text-sm disabled:bg-neutral-300 disabled:cursor-wait"
            >
              {isGenerating ? (
                <>
                  <span className="h-4 w-4 rounded-full border-2 border-white/20 border-t-white animate-spin"></span>
                  Contacting Gateway Services...
                </>
              ) : (
                <>
                  <Lock className="h-4 w-4 text-kiwi" />
                  Generate {gateway === "stripe" ? "Stripe" : gateway === "paystack" ? "Paystack" : "M-Pesa Direct (0745892776)"} Session • ${grandTotal.toFixed(2)}
                </>
              )}
            </button>
          </form>

          {/* Right Column: Order Summary Checklist (Col Span 5) */}
          <div className="lg:col-span-5 space-y-6">
            <div className="bg-neutral-50 rounded-lg p-6 border border-neutral-150 space-y-4">
              <h3 className="text-xs font-mono uppercase tracking-widest text-neutral-400 font-bold mb-2">
                Order Specifications ({resolvedItems.length})
              </h3>

              {/* Items listing scrolls */}
              <div className="divide-y divide-neutral-150 max-h-80 overflow-y-auto pr-1">
                {resolvedItems.map(({ item, product, variant }) => {
                  const price = variant!.priceOverride ? Number(variant!.priceOverride) : product!.basePrice;
                  const displayImage = product?.images[0]?.url || "https://via.placeholder.com/150";

                  return (
                    <div key={item.variantId} className="flex gap-4 py-3 first:pt-0">
                      <div className="h-16 w-12 rounded overflow-hidden border border-neutral-200 shrink-0 bg-white">
                        <img
                          src={displayImage}
                          alt={product!.name}
                          className="h-full w-full object-cover"
                          referrerPolicy="no-referrer"
                        />
                      </div>
                      <div className="flex-1 text-xs">
                        <h4 className="font-bold text-neutral-900 line-clamp-1">{product!.name}</h4>
                        <p className="text-[10px] text-neutral-400 font-mono mt-0.5 capitalize">
                          {variant!.color} // {variant!.size}
                        </p>
                        <div className="flex justify-between items-center mt-1">
                          <span className="text-neutral-500">Qty: {item.quantity}</span>
                          <span className="font-mono font-bold text-neutral-800">${(price * item.quantity).toFixed(2)}</span>
                        </div>
                      </div>
                    </div>
                  );
                })}
              </div>

              {/* Calculations layout */}
              <div className="border-t border-neutral-150/60 pt-4 space-y-2 text-xs text-neutral-500 font-sans">
                <div className="flex justify-between">
                  <span>Cart Items Subtotal</span>
                  <span className="font-mono text-neutral-800 font-medium">${subtotal.toFixed(2)}</span>
                </div>
                <div className="flex justify-between">
                  <span>Guaranteed VAT (8%)</span>
                  <span className="font-mono text-neutral-800 font-medium">${taxCost.toFixed(2)}</span>
                </div>
                <div className="flex justify-between">
                  <span>Delivery Dispatch Cargo</span>
                  <span className="font-mono text-neutral-800 font-medium">
                    {shippingCost === 0 ? "Complimentary" : `$${shippingCost.toFixed(2)}`}
                  </span>
                </div>
                <div className="flex justify-between border-t border-neutral-200 pt-3 text-sm font-bold text-dark font-sans">
                  <span>Grand Total Outlay</span>
                  <span className="font-mono text-neutral-950 text-base">${grandTotal.toFixed(2)}</span>
                </div>
              </div>
            </div>

            {/* SSL Insignia panel */}
            <div className="rounded-lg border border-neutral-150/60 p-4 flex gap-3 text-xs text-neutral-500 bg-white font-sans items-center">
              <ShieldCheck className="h-8 w-8 text-kiwi shrink-0" />
              <div>
                <span className="font-bold text-neutral-800 block uppercase text-[10px] tracking-wider leading-none mb-1">Authenticated Encryption</span>
                All billing calculations are processed utilizing industry standard AES-256 SSL tunnels. We persist no payment credentials locally.
              </div>
            </div>
          </div>

        </div>
      )}

    </div>
  );
}
